import { test, expect } from '@playwright/test';

test("Amazon Shopping Experience", async ({ page }) => {
  await page.goto("https://www.amazon.com");
  // await expect(page.locator("role=heading[name='Welcome to Amazon']")).toBeVisible();
  await page.locator("#twotabsearchtextbox").fill("wireless headphones");
  await page.locator("css=#nav-search-submit-button").click();
  await expect(page.getByText("Results")).toBeVisible();
  await page.locator("css=.s-result-item:nth-child(1) .s-title-instructions-style").click();
  await expect(page.getByText("Add to Cart")).toBeVisible();
  await page.getByText("Add to Cart").click();
  await expect(page.getByText("Added to Cart")).toBeVisible();
  await page.getByText("Continue Shopping").click();
  await page.locator("css=#nav-logo").click();
  await page.locator("#twotabsearchtextbox").fill("laptop stand");
  await page.locator("css=#nav-search-submit-button").click();
  await expect(page.getByText("Search results for laptop stand")).toBeVisible();
  await page.locator("css=.s-result-item:nth-child(2) .s-title-instructions-style").click();
  await expect(page.getByText("Add to Cart")).toBeVisible();
  await page.getByText("Add to Cart").click();
  await expect(page.getByText("Added to Cart")).toBeVisible();
  await page.getByText("View Cart").click();
  await expect(page.getByText("Shopping Cart")).toBeVisible();
  await expect(page.getByText("2 items")).toBeVisible();
  await page.getByText("Proceed to checkout").click();
  await expect(page.locator("role=heading[name='Sign in']")).toBeVisible();
  await page.locator("#ap_email").fill("customer@example.com");
  await page.getByText("Continue").click();
  await page.locator("#ap_password").fill("password123");
  await page.getByText("Sign in").click();
  await expect(page.getByText("Checkout")).toBeVisible();
  await page.getByText("Add a new address").click();
  await page.locator("#address-ui-widgets-enterAddressFullName").fill("John Doe");
  await page.locator("#address-ui-widgets-enterAddressPhoneNumber").fill("555-123-4567");
  await page.locator("#address-ui-widgets-enterAddressLine1").fill("123 Main Street");
  await page.locator("#address-ui-widgets-enterAddressCity").fill("New York");
  await page.locator("css=#address-ui-widgets-enterAddressStateOrRegion-dropdown-nativeId option[value='NY']").click();
  await page.locator("#address-ui-widgets-enterAddressPostalCode").fill("10001");
  await page.getByText("Use this address").click();
  await expect(page.getByText("Payment method")).toBeVisible();
  await page.getByText("Add a payment method").click();
  await page.locator("#addCreditCardNumber").fill("4111111111111111");
  await page.locator("#ccName").fill("John Doe");
  await page.locator("css=#ccMonth option[value='12']").click();
  await page.locator("css=#ccYear option[value='2025']").click();
  await page.locator("#ccCvc").fill("123");
  await page.getByText("Add your card").click();
  await expect(page.getByText("Review your order")).toBeVisible();
  await expect(page.getByText("wireless headphones")).toBeVisible();
  await expect(page.getByText("laptop stand")).toBeVisible();
  await page.getByText("Place your order").click();
  await expect(page.locator("role=heading[name='Thank you for your order!']")).toBeVisible();
  await expect(page.getByText("We'll send you an email confirmation")).toBeVisible();
  await page.getByText("Continue shopping").click();
  await expect(page.locator("role=heading[name='Welcome to Amazon']")).toBeVisible();
});